on:
  push:
    # Na main: zawsze i wszystko
    branches:
      - main

  # Na dev: tylko jezeli zmienił sie frontend
  pull_request:
    branches:
      - dev
    paths:
      - 'frontend/**' # Uruchom tylko, jeśli zmienił się frontend